# Generated by Django 5.2.3 on 2025-08-12 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('registered', 'Carta Registrada'), ('unregistered', 'Carta No Registrada')], max_length=20)),
                ('game', models.CharField(blank=True, choices=[('pokemon', 'Pokémon'), ('yugioh', 'Yu-Gi-Oh!')], max_length=20, null=True)),
                ('card_id', models.IntegerField(blank=True, null=True)),
                ('card_name', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(upload_to='post_photos/')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('for_sale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
