# Generated by Django 5.2.3 on 2025-08-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('type', models.TextField(blank=True)),
                ('ability_info', models.TextField(blank=True)),
                ('ability_effect', models.TextField(blank=True)),
                ('attack_1_info', models.TextField(blank=True)),
                ('attack_1_effect', models.TextField(blank=True)),
                ('attack_2_info', models.TextField(blank=True)),
                ('attack_2_effect', models.TextField(blank=True)),
                ('effect', models.TextField(blank=True)),
                ('number_rarity', models.TextField(blank=True)),
                ('weakness_ressistance_retreat', models.TextField(blank=True)),
                ('extracted_from', models.TextField(blank=True)),
                ('image', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Pokémon Card',
                'verbose_name_plural': 'Pokémon Cards',
                'db_table': 'cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonSet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=100)),
                ('printed_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('legal', models.BooleanField(default=True)),
                ('ptcgo_code', models.CharField(blank=True, max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('symbol', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Pokémon Set',
                'verbose_name_plural': 'Pokémon Sets',
                'db_table': 'sets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YuGiOhCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('attribute', models.TextField(blank=True)),
                ('effect', models.TextField(blank=True)),
                ('specie_and_others', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('atk', models.TextField(blank=True)),
                ('defs', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('level', models.TextField(blank=True)),
                ('p_scale', models.TextField(blank=True)),
                ('p_scale_effect', models.TextField(blank=True)),
                ('img_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Yu-Gi-Oh! Card',
                'verbose_name_plural': 'Yu-Gi-Oh! Cards',
                'db_table': 'cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YuGiOhCardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('rarity', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Yu-Gi-Oh! Card-Set Link',
                'verbose_name_plural': 'Yu-Gi-Oh! Card-Set Links',
                'db_table': 'card_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YuGiOhSet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Yu-Gi-Oh! Set',
                'verbose_name_plural': 'Yu-Gi-Oh! Sets',
                'db_table': 'sets',
                'managed': False,
            },
        ),
    ]
